# Use the official Node.js image with Alpine Linux
FROM node:alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

Run npm install next
# Install dependencies
RUN npm install


# Copy the rest of the application code
COPY . .

# Expose the port on which your application will run
EXPOSE 3000

# Run the application
CMD ["npm", "run", "dev"]
